# Generated by Django 5.2.3 on 2025-06-25 06:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='IN', max_length=50),
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='weather_api.city'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='SavedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='weather_api.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
